on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: rector

jobs:
  rector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: frankenphp
          ini-values: memory_limit=-1
          coverage: none
          tools: composer:v2

      - name: Install dependencies
        run: composer update --no-interaction --no-progress --optimize-autoloader --ansi --ignore-platform-req=ext-frankenphp

      - name: Run rector
        run: vendor/bin/rector process --no-progress-bar --dry-run --ansi
